### ISSUE TITLE
Is there a way to use custom eslint config files?

### ISSUE THREAD

**Issue by Prendo93** [videojs/spellbook#106]
I want to use some ecmaVersion 8 syntax in a plugin and linting fails on that line because the current eslint rulesheet is pegged at version 6 - is it possible to use custom eslint config files with sb-lint options?

**Comment by gkatsev** [comment]
Unfortunately, this project is no longer maintained. You can check out the latest version of videojs-standard which allows the newer ecma syntaxes.
